### ISSUE TITLE
customized window colors for error, warning and information

### ISSUE THREAD

**Issue by hwclass** [pburtchaell/react-notification#113]
## Code Example
```javascript
<Notification
          isActive={this.state.isActive}
          message="Notification"
          action="Dismiss"
          type="error" /*info, warning, and etc.*/
          title="Title!"
          onDismiss={this.toggleNotification.bind(this)}
          onClick={() =>  this.setState({ isActive: false })}
        />
```

## Expected behavior
By adding this, we can have some notification windows customized by styling. For example today, this notification window comes defaultly with a white text with a black background. Maybe after adding "error" string for a "type" property, it can become red and if info, it can be light blue and so on. So we need a type property and a string value to fill it, maybe.

## Actual Behavior
The default notification window comes with no configuration so default (black & white).

**Comment by pburtchaell** [comment]
> By adding this, we can have some notification windows customized by styling.  

I understand the need for this, but adding a type property for each style would add a lot of bloat to the library. In order to configure/customize the style, I would suggest using the `barStyle`, `activeBarStyle` and other style props. 

These are [documented](https://github.com/pburtchaell/react-notification/blob/master/docs/guides/props.md#for-single-notification-component).
