### ISSUE TITLE
Two children with the same key

### ISSUE THREAD

**Issue by AymericG** [pburtchaell/react-notification#121]
I am getting this error when using a React component in lieu of message: https://gyazo.com/47207e774cf5a7de5226995e5c73e002

My code preparing the message props: https://gyazo.com/c9c8b3f40ed7eaee50f22738e61e0e8b

What am I missing?

**Comment by AymericG** [comment]
It happens when I show multiple notifications, and one of them is 'leaving'

**Comment by pburtchaell** [comment]
The error message you've provided doesn't have anything to do with the `message` prop. You're passing in two notifications with the same key `0` and that's throwing an error in React. Can you provide more code, preferably the entire component in JSBin?

**Comment by AymericG** [comment]
​I have tried adding key in multiple places (note that it works when I only
use text):

This is my render function:
https://gyazo.com/ed3de1272815e55bece1b2b8c9a4a8e4
This is my mapToStateProps function:
https://gyazo.com/1fdb5e754841d65955fee46452b60fb5
This is my addNotification function:
https://gyazo.com/0201ce96a712f37372ca5018ac3ead9d


*Aymeric* Gaurat-Apelli
Founder of WeekPlan
http://weekplan.net

**Comment by pburtchaell** [comment]
The `key` doesn't go on the message. It should be included in the notification object ([see example](https://github.com/pburtchaell/react-notification/blob/master/examples/notification-tree/index.js#L30)). You'll want to update your `mapStateToProps` function to fix this.

This error is caused by you having two notifications with the same key and isn't an issue with the library. Make sure you never have two notifications with the key `0`.

On a side note, when you include code examples it's more helpful to put code in the comment itself. Links to screenshots are not particularly helpful because I can't copy/paste your code and I have to switch between tabs to see each screenshot. Thanks!

**Comment by AymericG** [comment]
Thanks for the great help. Found out that my reducer was setting the key property incorrectly. It is working now.

(And yes, sorry for the screenshots.)
