### ISSUE TITLE
Actions Link on NotificationStack

### ISSUE THREAD

**Issue by markortiz** [pburtchaell/react-notification#46]
I would like to add an `x` or `close` link on `NotificationStack`.
Currently, `NotificationStack` will just fade away after several secs that is set.
How can I stack multiple `Notification` with `action` and `onClick` props?

**Comment by pburtchaell** [comment]
As of right now, there is no way to have an `action` and `onClick` on the notifications due to issues it would cause with the timing and animations on the stack. This is certainly something I would like to add in the future, but as of present, I did not have the resources to implement it in this version. I am going to mark this as an enhancement as it is certainly something to work on in the next version.

**Comment by markortiz** [comment]
Cool! Looking forward to it!

**Comment by pburtchaell** [comment]
This is released in version 5.0.3.
