### ISSUE TITLE
Dynamic Notification on action dispatch

### ISSUE THREAD

**Issue by Vivekbhusal** [pburtchaell/react-notification#53]
Can you please help me understand. How can I display Notification after a dispatch of action? Let say, I want to display "UNDO" notification after I dispatch "delete" action.

An example would be very helpful.

**Comment by pburtchaell** [comment]
What are you using flux or Redux? It is hard to explain how to approach this without more context. I generally approach this in my apps (where I use Redux) by having a notification reducer that is connected to the `<Notification />` component. Whenever I want the notification to show, I dispatch an action that described the notification message, action and onClick handler. The onClick handler in this action is an action creator. In the case of your app, this could be the `UNDO` action creator you described. When the notification is clicked, the action creator is fired.

**Comment by pburtchaell** [comment]
I am closing this issue because the question is outside the scope of the project and I am not sure I will be able to help you more. If you need further assistance I would recommend a different source such as StackExchange or [the Redux community on Discord](https://discordapp.com/invite/0ZcbPKXt5bZ6au5t). :smile:
