### ISSUE TITLE
NotificationStack dismissAfter:false not working

### ISSUE THREAD

**Issue by achtan** [pburtchaell/react-notification#96]
{dismissAfter:false} not working, notification will autohide after 2s 
(continue of #88 )

**Comment by pburtchaell** [comment]
There is a pull request open at #94.

**Comment by pburtchaell** [comment]
Your issue does not follow the contributing guidelines for this project. Please review these guidelines, then update and reopen your issue.

**Comment by achtan** [comment]
:D

**Comment by achtan** [comment]
you added guidelines on Oct 8 and issue was created on Sep 20... so i will not recreate the issue, if it is not in you intention to fix you product, i dont rly case...

**Comment by pburtchaell** [comment]
Guidelines have existed since before September 20. On October 9, I expanded those guidelines with more information directly related to issues. 

Regardless, as I commented on #90, this feature works as expected. I could be mistaken, but I've verified [the test](https://github.com/pburtchaell/react-notification/blob/master/test/notification.js#L239) and [added a permanent notification to the example](https://github.com/pburtchaell/react-notification/commit/6e0507262942ca499ef4623ec272bcd3250fe3b1).

If this is not the case, [open a new issue](https://github.com/pburtchaell/react-notification/blob/master/.github/CONTRIBUTING.md#found-a-bug) with the details needed for me to help you.
